name: Create Preview Draft from PR
on:
  pull_request:
    branches: ['main']
permissions:
  contents: read
  pull-requests: write
jobs:
  draft:
    uses: curvenote/actions/.github/workflows/draft.yml@v1
    with:
      venue: curious-beams
      kind: article
      collection: articles
      id-pattern-regex: '^curious-beams-[a-zA-Z0-9_-]+$'
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
